[pytest]
python_files = tests.py test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
addopts =
    --cov=core_api
    --cov-report=html
    --cov-report=term-missing
    --cov-branch
testpaths = core_api
markers =
    django_db: mark test as requiring database

